CREATE TABLE MEMBER(
	ID BIGINT AUTO_INCREMENT,
	EMAIL VARCHAR(100) UNIQUE NOT NULL,
	FIRST_NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100) NOT NULL,
	PHOTO_URL VARCHAR(1000),
	HIRE_DATE DATE NOT NULL,
	CONSTRAINT MEMBER_PK PRIMARY KEY (ID)
);