CREATE TABLE TITLE(
	ID BIGINT UNIQUE NOT NULL,
	NAME VARCHAR(200) UNIQUE NOT NULL,
	DESCRIPTION VARCHAR(500) UNIQUE NOT NULL,
	CONSTRAINT TITLE_PK PRIMARY KEY (ID)
);

CREATE TABLE MEMBER(
	ID BIGINT AUTO_INCREMENT,
	FIRST_NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100) NOT NULL,
	PHOTO_URL VARCHAR(1000),
	TITLE_ID BIGINT NOT NULL, 
	HIRE_DATE DATE NOT NULL,
	CONSTRAINT MEMBER_PK PRIMARY KEY (ID),
	CONSTRAINT FK_TITLE FOREIGN KEY (TITLE_ID) REFERENCES TITLE(ID)
);

CREATE TABLE CONTACT_TYPE(
	ID BIGINT UNIQUE NOT NULL,
	NAME VARCHAR(100) UNIQUE NOT NULL,
	PRIORITY INT NOT NULL DEFAULT 99,
	CONSTRAINT CONTACT_TYPE_PK PRIMARY KEY (ID)
);

CREATE TABLE MEMBER_CONTACT(
	ID BIGINT AUTO_INCREMENT,
	MEMBER_ID BIGINT NOT NULL,
	CONTACT_TYPE_ID BIGINT NOT NULL,
	VALUE VARCHAR(200) UNIQUE NOT NULL,
	CONSTRAINT MEMBER_CONTACT_PK PRIMARY KEY (ID),
	CONSTRAINT FK_CONTACT_TYPE FOREIGN KEY (CONTACT_TYPE_ID) REFERENCES CONTACT_TYPE(ID),
	CONSTRAINT FK_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(ID)
);