INSERT INTO TITLE(ID, NAME, DESCRIPTION) VALUES(1,'CEO','Chief Executive Officer');
INSERT INTO TITLE(ID, NAME, DESCRIPTION) VALUES(2,'CTO','Chief Technical Officer');
INSERT INTO TITLE(ID, NAME, DESCRIPTION) VALUES(3,'CFO','Chief Financial Officer');
INSERT INTO TITLE(ID, NAME, DESCRIPTION) VALUES(4,'PM', 'Project Manager');
INSERT INTO TITLE(ID, NAME, DESCRIPTION) VALUES(5,'Senior', 'Senior Sofware Developer');
INSERT INTO TITLE(ID, NAME, DESCRIPTION) VALUES(6,'Middle', 'Middle Sofware Developer');
INSERT INTO TITLE(ID, NAME, DESCRIPTION) VALUES(7,'Junior', 'Junior Sofware Developer');

INSERT INTO CONTACT_TYPE(ID, NAME, PRIORITY) VALUES(1,'E-MAIL',1);
INSERT INTO CONTACT_TYPE(ID, NAME, PRIORITY) VALUES(2,'MOBILE',2);
INSERT INTO CONTACT_TYPE(ID, NAME, PRIORITY) VALUES(3,'SKYPE',3);
INSERT INTO CONTACT_TYPE(ID, NAME, PRIORITY) VALUES(4,'PERSONAL E-MAIL',DEFAULT);
INSERT INTO CONTACT_TYPE(ID, NAME, PRIORITY) VALUES(5,'PERSONAL MOBILE',DEFAULT);

INSERT INTO MEMBER(ID, FIRST_NAME, LAST_NAME, PHOTO_URL, TITLE_ID, HIRE_DATE) VALUES(1,'Denis', 'Danov', 'https://dreamix.eu/images/team/Denis_Danov_Java-Expert.jpg',5,parsedatetime('2013-07-08 10:00:00', 'yyyy-MM-dd HH:mm:ss'));

INSERT INTO MEMBER_CONTACT(MEMBER_ID, CONTACT_TYPE_ID, VALUE) VALUES(1,1,'denis.danov@dreamix.eu');
INSERT INTO MEMBER_CONTACT(MEMBER_ID, CONTACT_TYPE_ID, VALUE) VALUES(1,2,'+359 888 55 55 55');
INSERT INTO MEMBER_CONTACT(MEMBER_ID, CONTACT_TYPE_ID, VALUE) VALUES(1,3,'java_dev');